POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Vitor Figueiredo",
  "email": "teste@gmail.com"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "André Figueiredo",
  "email": "andre@gmail.com"
}